### ISSUE TITLE
Branch links left dead after branch removal

### ISSUE THREAD

**Issue by chrysn** [martinthomson/i-d-template#302] opened 2021-08-31 14:25 UTC
Working on https://github.com/anr-bmbf-pivot/draft-dns-over-coap I got complaints about dead links; it seems that when branches are removed after merging, parts are removed but the index stays.

I'll investigate later, and file a PR if I manage to find out the details.

**Comment by MikeBishop** [comment] 2021-08-31 16:45
Here's the code in question:

	# Clean up obsolete directories (2592000 = 30 days)
	@CUTOFF=$$(($$(date '+%s')-2592000)); \
	MAYBE_OBSOLETE=`comm -13 <(git branch -a | sed -e 's,.*[ /],,' | sort | uniq) <(ls $(GHPAGES_ROOT) | sed -e 's,.*/,,')`; \
	for item in $$MAYBE_OBSOLETE; do \
	  if [ -d "$(GHPAGES_ROOT)/$$item" ] && \
	     [ `git -C $(GHPAGES_ROOT) log -n 1 --format=%ct -- $$item` -lt $$CUTOFF ]; then \
	    echo "Remove obsolete '$$item'"; \
	    git -C $(GHPAGES_ROOT) rm -rfq -- $$item; \
	  fi \
	done

What it's supposed to do is remove artifacts from a branch when it no longer exists and they're more than 30 days old.

**Comment by martinthomson** [comment] 2021-09-01 01:26
I'm looking at https://anr-bmbf-pivot.github.io/draft-dns-over-coap/ and not seeing any dead links.

The code that Mike points at finds directories that exist on the gh-pages branch, but don't have matching branches.  It then removes the directory.  There is a second step where the index is regenerated, which is based on the directories that remain.

The only thing that might have caused problems here is that this cleanup might have been committed without updating the index.  Or if the index was generated before the cleanup happened.  That seems like it might be the cause of the problem.  (I am relying on dependency ordering here more than is appropriate; I'll see if a small update will fix that.)

**Comment by AkroutiHamza** [comment] 2021-12-30 20:25
if you add more doc then will be ok

**Closed** 2024-10-15 02:50 UTC
