### ISSUE TITLE
make ghpages fail

### ISSUE THREAD

**Issue by fpalombini** [martinthomson/i-d-template#96] opened 2017-03-23 10:18 UTC
Hi Martin,

I'm having a problem I don't understand with the Travis build, that appeared yesterday: 
https://travis-ci.org/core-wg/oscoap/builds/213763017

Also when I try to run make ghpages manually I get this errors:

```
git fetch -q origin gh-pages:gh-pages
git clone -q -b gh-pages . /tmp/ghpages1548
/usr/bin/sh: command substitution: line 1: syntax error near unexpected token `('
/usr/bin/sh: command substitution: line 1: `comm -13 <(git branch -a | sed -e 's,.*[ /],,' | sort | uniq) <(ls /tmp/ghpages1548 | sed -e 's,.*/,,')'
cp draft-ietf-core-object-security.html index.html
cp -f index.html /tmp/ghpages1548/index.html
cp: cannot create regular file ‘/tmp/ghpages1548/index.html’: No such file or directory
make: *** [/tmp/ghpages1548/index.html] Fel 1
```

Any help is much appreciated, as usual! :)

Francesca

**Comment by martinthomson** [comment] 2017-03-23 10:23
Ahh, that's the result of running an old shell.  It's a little strange given that this should be using bash as a shell.  A little more info about your system might help here.  Run ` /usr/bin/sh --version`.  On my system that shows bash version 4, but I'm running Linux.

**Comment by fpalombini** [comment] 2017-03-23 12:31
that's the output:

```
 $ /usr/bin/sh --version
GNU bash, version 4.3.42(5)-release (x86_64-pc-msys)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
does it help know that I'm using Git for Windows maybe?

**Comment by martinthomson** [comment] 2017-03-24 05:15
Hmm, interesting.  That's a fairly new version of bash, which should support the syntax this uses.

Does this work for you?  `diff <(echo 1) <(echo 2)` gives me:
```diff
1c1
< 1
---
> 2
```

...but the default shell on mac (bash 3.2.57) gives the same error you are seeing.

I'll try to find a way to construct a replacement for the command that doesn't rely on this syntax, but that might take some time.

(Sorry about latency, I'm plane hopping on the way to Chicago.  I'd try this myself, but my Windows machine doesn't move.)

**Comment by fpalombini** [comment] 2017-03-24 11:33
No problem, on the contrary, thank you for being very reactive :)
Yes, the diff works, I get the same output as you.
I also tried to do a make ghpages again, and I get this output now:

```
$ make ghpages
git fetch -q origin gh-pages:gh-pages
git clone -q -b gh-pages . /tmp/ghpages9032
/usr/bin/sh: command substitution: line 1: syntax error near unexpected token `('
/usr/bin/sh: command substitution: line 1: `comm -13 <(git branch -a | sed -e 's,.*[ /],,' | sort | uniq) <(ls /tmp/ghpages9032 | sed -e 's,.*/,,')'
git -C /tmp/ghpages9032 add -f /tmp/ghpages9032
if test `git -C /tmp/ghpages9032 status --porcelain | grep '^[A-Z]' | wc -l` -gt 0; then \
          git -C /tmp/ghpages9032  commit -m "Script updating gh-pages from a574366. [ci skip]"; fi
fatal: Cannot change to 'C:/Users/efrapal/AppData/Local/Temp/ghpages9032': No such file or directory
git -C /tmp/ghpages9032 push origin gh-pages
Everything up-to-date
rm -rf /tmp/ghpages9032
```

By the way, I was surprised to see that https://github.com/core-wg/oscoap/tree/gh-pages has changed, and now there is one folder for each commit updating ghpages... is that wanted?

(There  is no urgency btw, just wanted to record this issue somewhere)

**Comment by martinthomson** [comment] 2017-03-25 21:37
The extra commits are fixed in 1254390a455ac949f6637b3282bb23ffbd890785.

**Comment by fpalombini** [comment] 2017-03-31 18:06
Thanks Martin.

An update (in case it would be useful) make ghpages now outputs this:

```
$ make ghpages
git fetch -q origin gh-pages:gh-pages
git clone -q -b gh-pages . /tmp/ghpages12276
/usr/bin/sh: command substitution: line 1: syntax error near unexpected token `('
/usr/bin/sh: command substitution: line 1: `comm -13 <(git branch -a | sed -e 's,.*[ /],,' | sort | uniq) <(ls /tmp/ghpages12276 | sed -e 's,.*/,,')'
XML_RESOURCE_ORG_PREFIX=https://xml2rfc.tools.ietf.org/public/rfc kramdown-rfc2629 draft-ietf-core-object-security.md > draft-ietf-core-object-security.xml
xml2rfc -q draft-ietf-core-object-security.xml -o draft-ietf-core-object-security.htmltmp --html
sed -f lib/addstyle.sed draft-ietf-core-object-security.htmltmp > draft-ietf-core-object-security.html
xml2rfc -q draft-ietf-core-object-security.xml -o draft-ietf-core-object-security.txt --text
cp draft-ietf-core-object-security.html index.html
cp -f index.html /tmp/ghpages12276/index.html
cp: cannot create regular file ‘/tmp/ghpages12276/index.html’: No such file or directory
make: *** [/tmp/ghpages12276/index.html] Fel 1
rm draft-ietf-core-object-security.htmltmp draft-ietf-core-object-security.xml
```


Also, trying to set up a new repo, I get this error when I run setup ghpages (don't know if it's related or not, please tell me if you'd rather I open another issue):

```
$ make -f lib/setup.mk setup-ghpages      
Initializing gh-pages branch
git clone -n . /tmp/ghpages6764
Cloning into '/tmp/ghpages6764'...
done.
git -C /tmp/ghpages6764 checkout -q --orphan gh-pages
git -C /tmp/ghpages6764 rm -rfq .
Creating index.html and circle.yml
touch: cannot touch ‘/tmp/ghpages6764/index.html’: No such file or directory
make: *** [setup-ghpages] Fel 1
```

**Comment by martinthomson** [comment] 2017-04-05 05:08
I now have access to Git for Windows and I can confirm that `diff <(echo 1) <(echo 2)` fails when running `/usr/bin/sh`.  I'm interested in learning how you managed to install `make` though.  The default installation doesn't come with anything like that and it appears as though it is ignoring the `SHELL` variable that I explicitly set.

BTW, I now know how to work around this, but the fix is extremely verbose.  For later...

```
x=$(mktemp /tmp/XXXXXX);trap 'rm -f $x' exit err; command1 >$x &; command2 | comm -13 $x -
```

Much easier if make were to respect $SHELL so that we could get a shell that supports process substitution.

**Comment by fpalombini** [comment] 2017-04-05 11:02
Yes, that was annoying (installing make), but I was really tired of switching from windows to linux...
Sorry I just realized that when I said Git for Windows I was wrong, and what I'm actually using is [msysgit](https://git.wiki.kernel.org/index.php/MSysGit%3aInstallMSysGit), which is different from Git for Windows.
It took some time and I don't remember exactly what my steps were, but I think [MinGW](http://www.mingw.org/wiki/Getting_Started) worked.

https://superuser.com/questions/701141/how-to-add-more-commands-to-git-bash-shell

**Comment by martinthomson** [comment] 2017-10-08 23:03
If this is still an issue, send me mail and we can work on it.

**Closed** 2017-10-08 23:02 UTC

**Comment by CxRes** [comment] 2023-09-06 23:54
I am having a near identical problem when running `make ghpages` from Git Bash on Windows.

```
$ make ghpages
git fetch -qf origin gh-pages:gh-pages
git clone -q -b gh-pages . /tmp/ghpages1215
fatal: cannot change to 'C:/Temp/ghpages1215': No such file or directory
fatal: cannot change to 'C:/Temp/ghpages1215': No such file or directory
/usr/bin/sh: line 4: [: -lt: unary operator expected
ls: cannot access '/tmp/ghpages1215': No such file or directory
cat draft-gupta-httpbis-per-resource-events.md  | mmark | lib/trace.sh draft-gupta-httpbis-per-resource-events.xml -s venue D:/dev/my-libs/internet-draft-per-resource-events/lib/.venv/Scripts/er-resource-events/lib/.venv/Scripts/python lib/add-note.py | lib/trace.sh draft-gupta-httpbis-per-resource-events.xml -s v2v3 D:/dev/my-libs/internet-drafts/xml2rfc -q --rfc-base-url https://t-per-resource-events/lib/.venv/Scripts/xml2rfc -q --rfc-base-url https://www.rfc-editor.org/rfc/ --id-base-url https://datatracker.ietf.org/doc/html/ --cagupta-httpbis-per-resource-events.xmlche=C:\Users\Rahul/.cache/xml2rfc --v2v3 /dev/stdin -o /dev/stdout >draft-gupta-httpbis-per-resource-events.xml
No such file: /proc/self/fd/0
make: *** [lib/main.mk:70: draft-gupta-httpbis-per-resource-events.xml] Error 1
make: *** Deleting file 'draft-gupta-httpbis-per-resource-events.xml'
```


```
$ bash --version
GNU bash, version 5.2.12(1)-release (x86_64-pc-msys)
```

**Comment by martinthomson** [comment] 2023-09-07 00:03
msys is not really supported here.  Take a look at the error messages:

```
git clone -q -b gh-pages . /tmp/ghpages1215
fatal: cannot change to 'C:/Temp/ghpages1215': No such file or directory
```

I'm inferring from this that what is happening is that `/tmp` is mapped somehow to `c:\Temp`, but the translation is getting mixed up in the middle and consequently git is getting confused.

I recommend [WSL2](https://learn.microsoft.com/en-us/windows/wsl/install) for this.

**Comment by CxRes** [comment] 2023-09-07 00:34
Yes, I investigated a bit more.

`git clone` writes to `D:\tmp\ghpagesxxxx` and then the script is looking for the files in `C:\tmp\ghpagesxxxx`, (since I keep all my work on `D:`). I tried changing the `GHPAGES_ROOT` to `/d/temp/ghpages$(PID)` and that wrote to `D:\d\tmp\ghpagesxxxx`.

Using WSL2 is unfortunately not an option on my moderately ancient PC and limited disk space!

**Comment by martinthomson** [comment] 2023-09-07 02:24
A baseline WSL2 with reasonable tooling installed seems to weigh in at about 2G, so I understand that.  Let me know if there is anything I can do to make this MSYS compatible.  I can't promise much, but I will take pull requests that will help.

**Comment by CxRes** [comment] 2023-09-07 12:32
I have not worked with Make in over a decade, even then my knowledge is minimal. I managed to bypass the error by hardcoding the path in `git clone` but a similar thing pops up again with `No such file: /proc/self/fd/0` in the file conversion proper. 

If I can figure out a more concrete proposal, I'll let you know... thanks!
